version: 2
jobs:
  build:
    docker:
      - image: ubuntu:disco
    steps:
      - checkout
      - run: |
          apt -y update --fix-missing
          apt -y upgrade
          apt -y install llvm
      - run: scripts/test.sh
